/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import DAO.DAO_Venta;
import Model.Ventas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose_Gonzalez
 */
public class BuscarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente() {
        initComponents();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPopupMenu();
        Seleccionar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        Menu.setComponentPopupMenu(Menu);

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        Menu.add(Seleccionar);

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, -1));

        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PATERNO", "MATERNO"
            }
        ));
        table.setComponentPopupMenu(Menu);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 570, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        seleccionarCliente();
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        getClienteBuscador();
    }//GEN-LAST:event_txtBuscarKeyReleased

    Ventas ventas = new Ventas();
    DAO_Venta $ventas = new DAO_Venta();
    
    private void getClienteBuscador() {
         limpiarTabla();
        DefaultTableModel tableCliente = (DefaultTableModel) table.getModel();
        String nombre = txtBuscar.getText();
        ArrayList<Ventas> clientes = $ventas.getAllClientByName(nombre);

        clientes.forEach((cliente) -> {
            System.out.println(cliente.getNombre());
            int fila = tableCliente.getRowCount();
            tableCliente.addRow(new Object[1]);
            tableCliente.setValueAt(cliente.getIdCliente(), fila, 0);
            tableCliente.setValueAt(cliente.getNombre(), fila, 1);
            tableCliente.setValueAt(cliente.getaPaterno(), fila, 2);
            tableCliente.setValueAt(cliente.getaMaterno(), fila, 3);
        });
    }
     
     public void limpiarTabla() {
        DefaultTableModel tableclientes = (DefaultTableModel) table.getModel();
        for (int filas = tableclientes.getRowCount() - 1; filas >= 0; filas--) {
            tableclientes.removeRow(filas);
        }
    }

    private void mostrarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();

        try {
            ArrayList<Ventas> lista = new ArrayList<Ventas>($ventas.getAllClient());
            int num = lista.size();
            modelo.setNumRows(num);
            for (int i = 0; i < lista.size(); i++) {
                modelo.setValueAt(lista.get(i).getIdCliente(), i, 0);
                modelo.setValueAt(lista.get(i).getNombre(), i, 1);
                modelo.setValueAt(lista.get(i).getaPaterno(), i, 2);
                modelo.setValueAt(lista.get(i).getaMaterno(), i, 3);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    private void seleccionarCliente(){
        String nom,ap,am;
        int seleccion = table.getSelectedRow();
            nom = (String)table.getValueAt(seleccion, 1);
            ap = (String)table.getValueAt(seleccion, 2);
            am = (String)table.getValueAt(seleccion, 3);
            
            //lnombreCliente.setText(nom+" "+ap+" "+am);
            //String nombre = jlnombreCliente.getText();
            Venta.txtCliente.setText(nom+" "+ap+" "+am);
            dispose();
            Venta.btnBuscarArticulos.setEnabled(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Menu;
    public javax.swing.JMenuItem Seleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
