/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Model.*;
import DAO.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author juana
 */
public class Empleados extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        getEmpelados();
        disabledButtons(btnAgregar);
        modelo = (DefaultTableModel) TableEmpleados.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuEmergente = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAmaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jcbCargo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        MenuEmergente.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.setActionCommand("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        MenuEmergente.add(Eliminar);

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Cargo"
            }
        ));
        TableEmpleados.setComponentPopupMenu(MenuEmergente);
        jScrollPane1.setViewportView(TableEmpleados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 735, 158));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 244, -1));

        jLabel3.setText("Apellido P:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));
        getContentPane().add(txtApaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 244, -1));

        jLabel4.setText("Apellido M:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));
        getContentPane().add(txtAmaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 244, -1));

        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 244, -1));

        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 20));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 244, -1));

        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 70, 20));

        jLabel8.setText("Direccion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 70, 20));

        jLabel9.setText("Cargo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 70, 20));

        jLabel10.setText("Usuario:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 70, 20));

        jLabel11.setText("Contraseña:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 70, 20));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 244, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 244, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 244, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 244, -1));

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Vendedor", "Cajero" }));
        getContentPane().add(jcbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 240, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, -1));

        btnGuardar.setText("Guardar Cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 170, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        modificarEmpleado();
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        eliminarEmpleado();
    }//GEN-LAST:event_EliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        registrarEmpleado();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardarEmpleado();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        deleteEmpleado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        resetVariables();
    }//GEN-LAST:event_btnCancelarActionPerformed

    Empleado getEmpleado = new Empleado();
    DAO_Empelado $empleados = new DAO_Empelado();

    private void deleteEmpleado() {
        if ($empleados.deleteEmpleado(getEmpleado)) {
            resetVariables();
            JOptionPane.showMessageDialog(null, "Se elimino el empleado");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }
    }

    private void guardarEmpleado() {
        Empleado empleado = new Empleado();
        empleado.setId_persona(getEmpleado.getId_persona());
        empleado.setAmaterno(txtAmaterno.getText());
        empleado.setApaterno(txtApaterno.getText());
        empleado.setCargo(String.valueOf(jcbCargo.getSelectedItem()));
        empleado.setContrasenia(txtContraseña.getText());
        empleado.setDireccion(txtDireccion.getText());
        empleado.setEdad(Integer.parseInt(txtEdad.getText()));
        empleado.setEmail(txtEmail.getText());
        empleado.setNombre(txtNombre.getText());
        empleado.setNombreUsuario(txtUsuario.getText());
        empleado.setTelefono(txtTelefono.getText());
        if ($empleados.updateEmpleado(empleado)) {
            resetVariables();
            JOptionPane.showMessageDialog(null, "Actualizacion Exitosa");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }
    }

    private void registrarEmpleado() {
        Empleado empleado = new Empleado();
        empleado.setAmaterno(txtAmaterno.getText());
        empleado.setApaterno(txtApaterno.getText());
        empleado.setCargo(String.valueOf(jcbCargo.getSelectedItem()));
        empleado.setContrasenia(txtContraseña.getText());
        empleado.setDireccion(txtDireccion.getText());
        empleado.setEdad(Integer.parseInt(txtEdad.getText()));
        empleado.setEmail(txtEmail.getText());
        empleado.setNombre(txtNombre.getText());
        empleado.setNombreUsuario(txtUsuario.getText());
        empleado.setTelefono(txtTelefono.getText());
        if ($empleados.createEmpleado(empleado)) {
            resetVariables();
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un error");
        }
    }

    private void resetVariables() {
        txtNombre.setText(null);
        txtAmaterno.setText(null);
        txtApaterno.setText(null);
        jcbCargo.setSelectedItem(null);
        txtContraseña.setText(null);
        txtDireccion.setText(null);
        txtEdad.setText(null);
        txtEmail.setText(null);
        txtTelefono.setText(null);
        txtUsuario.setText(null);
        getEmpelados();
        disabledButtons(btnAgregar);
    }

    private void modificarEmpleado() {
        int fila = TableEmpleados.getSelectedRow();
        modelo = (DefaultTableModel) TableEmpleados.getModel();
        if (fila != -1) {
            String id = String.valueOf(modelo.getValueAt(fila, 0));
            getEmpleado = $empleados.getOneByIDPersona(id);
            fillField(getEmpleado);
        }

        disabledButtons(btnGuardar);
    }

    private void eliminarEmpleado() {
        int fila = TableEmpleados.getSelectedRow();
        modelo = (DefaultTableModel) TableEmpleados.getModel();
        if (fila != -1) {
            String id = String.valueOf(modelo.getValueAt(fila, 0));
            getEmpleado = $empleados.getOneByIDPersona(id);
            fillField(getEmpleado);
        }
        disabledButtons(btnEliminar);
    }

    private void fillField(Empleado empleado) {
        txtNombre.setText(empleado.getNombre());
        txtAmaterno.setText(empleado.getAmaterno());
        txtApaterno.setText(empleado.getApaterno());
        jcbCargo.setSelectedItem(empleado.getCargo());
        txtContraseña.setText(empleado.getContrasenia());
        txtDireccion.setText(empleado.getDireccion());
        txtEdad.setText(String.valueOf(empleado.getEdad()));
        txtEmail.setText(empleado.getEmail());
        txtTelefono.setText(empleado.getTelefono());
        txtUsuario.setText(empleado.getNombreUsuario());
    }

    private void disabledButtons(JButton bottonAviable) {
        btnAgregar.setVisible(false);
        btnGuardar.setVisible(false);
        btnEliminar.setVisible(false);
        bottonAviable.setVisible(true);
    }

    private void getEmpelados() {
        limpiarTabla();
        DefaultTableModel tableEmpleado = (DefaultTableModel) TableEmpleados.getModel();
        ArrayList<Empleado> empleados = $empleados.getAll();

        empleados.forEach((empleado) -> {
            System.out.println(empleado.getNombre());
            int fila = tableEmpleado.getRowCount();
            tableEmpleado.addRow(new Object[1]);
            tableEmpleado.setValueAt(empleado.getId_persona(), fila, 0);
            tableEmpleado.setValueAt(empleado.getNombre(), fila, 1);
            tableEmpleado.setValueAt(empleado.getApaterno(), fila, 2);
            tableEmpleado.setValueAt(empleado.getCargo(), fila, 3);
        });
    }

    public void limpiarTabla() {
        DefaultTableModel tableEmpleado = (DefaultTableModel) TableEmpleados.getModel();
        for (int filas = tableEmpleado.getRowCount() - 1; filas >= 0; filas--) {
            tableEmpleado.removeRow(filas);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JPopupMenu MenuEmergente;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JTable TableEmpleados;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JTextField txtAmaterno;
    private javax.swing.JTextField txtApaterno;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
