/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Connection.DB_Manager;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jose_Gonzalez
 */
public class ReporteComision extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteComision
     */
    public ReporteComision() {
        initComponents();
    }

    public DB_Manager mysql = new DB_Manager();
    public Connection cn = mysql.getConnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMes = new com.toedter.calendar.JMonthChooser();
        jLabel2 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REPORTES DE COMISIONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));
        getContentPane().add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, -1));

        jLabel2.setText("Selecciona un mes:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        btnGenerarReporte.setText("Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        int mes = cbMes.getMonth() + 1;
        String mess = meses(mes);
        System.out.println(mes);
        System.out.println(mess);
        generarReporte(mes, mess);
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void generarReporte(int mes, String mess) {
        try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(Reportes.class.getResource("/Vistas/reporteComision.jasper"));

            HashMap<String, Object> parametro = new HashMap<>();
            parametro.put("mes", mes);
            parametro.put("mess", mess);

            JasperPrint jp = JasperFillManager.fillReport(jr, parametro, cn);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setTitle("Reporte de comisiones");
            jv.show();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "error" + e);
        }
    }
    
    private String meses(int mes){
        String mess = "";
        if (mes == 1) {
            mess = "ENERO";
        } else if (mes == 2) {
            mess = "FEBRERO";
        } else if (mes == 3) {
            mess = "MARZO";
        } else if (mes == 4) {
            mess = "ABRIL";
        } else if (mes == 5) {
            mess = "MAYO";
        } else if (mes == 6) {
            mess = "JUNIO";
        } else if (mes == 7) {
            mess = "JULIO";
        } else if (mes == 8) {
            mess = "AGOSTO";
        } else if (mes == 9) {
            mess = "SEPTIEMBRE";
        } else if (mes == 10) {
            mess = "OCTUBRE";
        } else if (mes == 11) {
            mess = "NOVIEMBRE";
        } else if (mes == 12) {
            mess = "DICIEMBRE";
        }
        return mess;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private com.toedter.calendar.JMonthChooser cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
